# Numpy Tutorial - Numerical Python

In [2]:
import numpy as np

In [3]:
# Numpy Array - Array is homogeneous
a= np.array([3,4,5])
a

array([3, 4, 5])

In [4]:
print(a)
print('Dimension = ',a.ndim) # Number of dimensions
print('Size = ',a.size) # Size
print('Shape = ',a.shape) # Shape
print('Element Type = ',a.dtype) # Data Type

[3 4 5]
Dimension =  1
Size =  3
Shape =  (3,)
Element Type =  int32


In [5]:
# Create a 2 dimensional array
a=np.array([[3,4,5],[6,7,8]])
a

array([[3, 4, 5],
       [6, 7, 8]])

In [6]:
print(a)
print('Dimension = ',a.ndim) # Number of dimensions
print('Size = ',a.size) # Size
print('Shape = ',a.shape) #Shape
print('Element Type = ',a.dtype) # Data Type

[[3 4 5]
 [6 7 8]]
Dimension =  2
Size =  6
Shape =  (2, 3)
Element Type =  int32


In [7]:
# Create (2,3,2)
b=np.array([
            [[1,2],[3,4],[5,6]]
            ,[[7,8],[9,10],[11,12]]
           ])
print(b)
print('Dimension = ',b.ndim) # Number of dimensions
print('Size = ',b.size) # Size
print('Shape = ',b.shape) #Shape
print('Element Type = ',b.dtype) # Data Type

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Dimension =  3
Size =  12
Shape =  (2, 3, 2)
Element Type =  int32


# Arange

In [8]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
np.arange(24).reshape(4,6)    

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [10]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [11]:
np.zeros((2,2)) # Creates an array full of zeros

array([[0., 0.],
       [0., 0.]])

In [38]:
np.ones((2,2),dtype=int) # Creates an array full of ones

array([[1, 1],
       [1, 1]])

# Linspace


In [3]:
np.linspace(10,50,5,dtype=int) # Linspace(start,end, number of elements) - Equally spaced sample data

array([10, 20, 30, 40, 50])

In [12]:
np.linspace(150,220,5)

array([150. , 167.5, 185. , 202.5, 220. ])

# Reshape

In [42]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [43]:
# Reshape for 81 elements
np.arange(81).reshape(3,3,9)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]],

       [[27, 28, 29, 30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49, 50, 51, 52, 53]],

       [[54, 55, 56, 57, 58, 59, 60, 61, 62],
        [63, 64, 65, 66, 67, 68, 69, 70, 71],
        [72, 73, 74, 75, 76, 77, 78, 79, 80]]])

In [44]:
np.arange(81).reshape(3,3,3,3)

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]]]])

In [15]:
#Create a 6 dimensional data with arange having 6 elements in 1 dimensions
d=np.arange(6).reshape(1,1,1,1,1,6)
d

array([[[[[[0, 1, 2, 3, 4, 5]]]]]])

In [16]:
print(d)
print('Dimension = ',d.ndim) # Number of dimensions
print('Size = ',d.size) # Size
print('Shape = ',d.shape) #Shape
print('Element Type = ',d.dtype) # Data Type

[[[[[[0 1 2 3 4 5]]]]]]
Dimension =  6
Size =  6
Shape =  (1, 1, 1, 1, 1, 6)
Element Type =  int32


# Ravel

In [17]:
d=d.ravel() # Ravel flatten any dimensional array into 1 dimensional array
d

array([0, 1, 2, 3, 4, 5])

In [18]:
print(d)
print('Dimension = ',d.ndim) # Number of dimensions
print('Size = ',d.size) # Size
print('Shape = ',d.shape) #Shape
print('Element Type = ',d.dtype) # Data Type

[0 1 2 3 4 5]
Dimension =  1
Size =  6
Shape =  (6,)
Element Type =  int32


# Random Numbers

In [54]:
np.random.rand()*100

31.8834443301675

In [56]:
int(np.random.rand()*100)  # Type-casting the values

99

In [57]:
np.random.rand(5)

array([0.10692925, 0.08145521, 0.94831464, 0.92810946, 0.22620458])

In [4]:
np.random.randint(35,100)

60

In [5]:
np.sqrt(np.random.randint(35,100,50).reshape(5,10))

array([[9.89949494, 8.1240384 , 8.66025404, 8.88819442, 6.40312424,
        6.8556546 , 7.48331477, 9.53939201, 8.1240384 , 9.38083152],
       [9.48683298, 7.        , 8.1240384 , 6.244998  , 9.16515139,
        7.34846923, 7.74596669, 7.21110255, 7.14142843, 9.16515139],
       [9.94987437, 6.164414  , 8.48528137, 8.71779789, 5.91607978,
        9.69535971, 8.18535277, 6.08276253, 9.11043358, 7.        ],
       [9.79795897, 7.48331477, 6.08276253, 7.74596669, 6.78232998,
        6.70820393, 7.21110255, 9.16515139, 8.54400375, 6.55743852],
       [7.74596669, 6.55743852, 8.42614977, 8.77496439, 9.43398113,
        6.40312424, 9.69535971, 8.42614977, 8.30662386, 7.74596669]])

In [6]:
np.sqrt(np.random.randint(0,100,1000000).reshape(100000,10))

array([[9.94987437, 3.87298335, 9.32737905, ..., 7.07106781, 7.93725393,
        9.        ],
       [8.30662386, 7.68114575, 9.32737905, ..., 9.16515139, 0.        ,
        3.        ],
       [8.94427191, 8.30662386, 8.06225775, ..., 9.69535971, 7.28010989,
        9.        ],
       ...,
       [5.74456265, 4.47213595, 8.77496439, ..., 3.46410162, 1.        ,
        4.47213595],
       [9.59166305, 5.        , 8.42614977, ..., 9.74679434, 4.35889894,
        4.47213595],
       [0.        , 4.79583152, 5.19615242, ..., 9.16515139, 9.59166305,
        9.43398113]])

In [65]:
np.round(4.6)

5.0

In [66]:
np.floor(4.2)

4.0

In [67]:
np.ceil(4.2)

5.0

In [68]:
np.log10(100)

2.0

# Horizontal split and Vertical Split

In [4]:
a=np.arange(24).reshape(4,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [5]:
np.hsplit(a,2)

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])]

In [6]:
np.hsplit(a,2)[0]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20]])

In [7]:
np.hsplit(a,2)[1]

array([[ 3,  4,  5],
       [ 9, 10, 11],
       [15, 16, 17],
       [21, 22, 23]])

In [8]:
np.vsplit(a,2)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [108]:
np.vsplit(a,2)[0]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [109]:
np.vsplit(a,2)[1]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [110]:
np.vsplit(a,2)[1][1][0]

18

# Horizontal Stack and Vertical Stack

In [19]:
a=np.arange(9).reshape(3,3)
b=np.arange(20,29).reshape(3,3)

In [20]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [113]:
b

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

In [114]:
np.hstack((a,b))

array([[ 0,  1,  2, 20, 21, 22],
       [ 3,  4,  5, 23, 24, 25],
       [ 6,  7,  8, 26, 27, 28]])

In [115]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

# Add two integers in an array and typecast it to float

In [9]:
a= np.array([2+5,3+2],dtype='float')
print(a)
print(a.dtype)

[7. 5.]
float64
